USE [master]
GO

/****** Object:  Database [CarRepair]    Script Date: 22.10.2020 15:46:52 ******/
CREATE DATABASE [CarRepair]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRepair', FILENAME = N'C:\t2\CarRepair.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CarRepair_log', FILENAME = N'C:\t2\CarRepair_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRepair].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRepair] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarRepair] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarRepair] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarRepair] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarRepair] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarRepair] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CarRepair] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRepair] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRepair] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRepair] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarRepair] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarRepair] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRepair] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarRepair] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRepair] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarRepair] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRepair] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRepair] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRepair] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRepair] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRepair] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarRepair] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRepair] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarRepair] SET  MULTI_USER 
GO

ALTER DATABASE [CarRepair] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRepair] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRepair] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRepair] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CarRepair] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRepair] SET QUERY_STORE = OFF
GO

USE [CarRepair]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CarRepair] SET  READ_WRITE 
GO

