USE [CarRepair]
GO

/****** Object:  Table [dbo].[Cars]    Script Date: 22.10.2020 15:49:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cars](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nuber] [nchar](15) NOT NULL,
	[Distance] [int] NOT NULL,
	[VolumeEngine] [int] NOT NULL,
	[IDOwner] [int] NOT NULL,
	[IDModel] [int] NOT NULL,
 CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNIQUE_Nuber] UNIQUE NONCLUSTERED 
(
	[Nuber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Cars]  WITH CHECK ADD  CONSTRAINT [FK_Cars_Models] FOREIGN KEY([IDModel])
REFERENCES [dbo].[Models] ([ID])
GO

ALTER TABLE [dbo].[Cars] CHECK CONSTRAINT [FK_Cars_Models]
GO

ALTER TABLE [dbo].[Cars]  WITH CHECK ADD  CONSTRAINT [FK_Cars_Owners] FOREIGN KEY([IDOwner])
REFERENCES [dbo].[Owners] ([ID])
GO

ALTER TABLE [dbo].[Cars] CHECK CONSTRAINT [FK_Cars_Owners]
GO

